version: '3'

services:
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: muser
      ME_CONFIG_BASICAUTH_PASSWORD: P@ssw0rd
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssw0rdRoot
    links:
      - mongo
    networks:
      - desafio-network

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rdRoot
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volumes:/data/db
    networks:
      - desafio-network

networks: 
    desafio-network:
      driver: bridge