
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: P@ssw0rdRoot
      database: challenge_db_dev
      port: 27017
      host: localhost
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
